site_name: open-event-server
repo_name: cecethea/open_event_server
repo_url: https://github.com/cecethea/open_event_server
site_dir: site
copyright: Copyright &copy; Fossasia.
dev_addr: 0.0.0.0:8001
edit_uri: ''
nav:
  - Home: 'index.md'
theme:
  name: material
  features:
    - tabs
  palette:
    primary: indigo
    accent: orange

markdown_extensions:
  - admonition